before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: WdcqYjs5uht66lHCgeaOQ0xOuek10ctPLKZ8HBlUvXP6CykCt950E7GnnbkbK74i5R8ydp4foHgba4ua2RF/QXRJN2fZWY44BrKvUV+Z9TxbBAUNeuOUj/CDzXHSSFhn8BE7A+M3tqXjEdvA8aAB6AHUEushi4eqtG+JV9NmXmcPW/eDF9LcK2KTGYE7d7Q6U81LYbzXYl7DPMDMT7RtESYlk+ObuA/7Yck/uZAeP0tZRX0XFnzBn2o608u7/3WndAkEoI3KJTu17uTLj8ygp2l8tMF3oxKXcKkZjl6ZaQSTYkiY392Or8l2pm4P1xnwH7uIaC4URaZ/m/Ukn8/nxokwqPTpZprtp5Vvbe5g46ASxi1azjiQfJ1AmK8vPsz8mL+QioLw48qqzGXYZdAQn8p93JGYorxP3MG+v070W91JTWYlTSnDQYLSXjB2zLpCh2lPo7OXTc8pjOG+l+rOjfG1JKYgQJnkqOPGq8DPAxPOIpc8QBoikR9oijIGT2LnmQxGCYVD66PQyHa5NHLo57gx6H30khR7aUIIMecIZQ2DCDiKFMwm9H5RX1XqcZNgr2DAQSmdMXbu6vOUGxJ2jcRlhmHMcIkJbKMLuKfckUpW193urS7KOrk9JCD723l8xy6e6N85k9+h1xnbIzzykjPvMAf3kicsXXZAt7ZtFSM= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
